args:
  image2video: False # True for image2video, False for text2video
  latent_channels: 16
  mode: inference
  batch_size: 1
  # input_type: loader
  # input_file: configs/test.txt
  sampling_image_size: [480, 720]
  sampling_num_frames: 13 # Must be 13, 11 or 9
  sampling_fps: 8
  bf16: True
  amp_exclude_key: ["quantizer"]
  force_inference: True
